### ISSUE TITLE
Some of my animals disapear

### ISSUE THREAD

**Issue by Cilleh1989** [capnkirok/animania#148]
Hi, I host a private server via Hamachi, and I'm new to this mod, but I do belive that animals aint suppose to just disapear without a trace?
After I got my animalpens up and running, I've lost 3 Bull's (Holstein, 2x Hereford) and 1 Cow (Hereford)
There is absolutly no trace of them anywhere, and I've got no clue on why it happens.
Is this something that you guys can fix? 
I use other mods on the server, and I'll provide a list, just in case it will help.

![modpack](https://cloud.githubusercontent.com/assets/28509378/25782491/92f1843e-334c-11e7-880b-9219300c75c0.png)

I hope you can fix it, if it is an issue.
But as far as I understand, you can have more than one Bull in a pen along with more than one cow, I two mateing couples. (Now one, since both cow and bull disapeard, Hereford)

- Cilleh1989

**Comment by capnkirok** [comment]
Sorry to hear. Could be a conflict, and it could be that you are at your spawn limit (set in the config). If the animal has not been hand fed or named, and you are exceeding your spawn limit, they have a chance of being removed. 

Easiest fix is to increase your spawn limit and hand feed (tame) or name your animals.

Can you tell me what version of the mod are you have installed, and what version of forge you are using?

**Comment by Cilleh1989** [comment]
The Bulls and the Cow that disapeared where named, come to think of it, I also lost some calves.
The mod version is: animania-1.10.2-1.0.4.7.jar
and the forge version is: forge-1.10.2-12.18.3.2281 

I'll look in the config and see if I can find the spawn limit and possibly change it, if that is the problem.
Thanks for the qucik reply

**Comment by Cilleh1989** [comment]
I've now changed the numbers from 1 to 4 on cows and pigs. The chickens haven't been a problem.
If this solves the issue, I'll let you know immediately

**Comment by Cilleh1989** [comment]
It didn't work, I just lost a named and handfeed Hereford cow..

**Comment by capnkirok** [comment]
Ok, thanks I will do some more testing. You are on the correct version. I didn't see that you changed the spawn limit though... just the family size. Under Spawn under the configs, there should be a spawn limit size for each species.

**Comment by Cilleh1989** [comment]
The spawn limit for cows (guessing bulls are included there?) is currently on 24. I do belive that is standart?
What do you suggest I change it to? :)

**Comment by Cilleh1989** [comment]
I changed it from 24 to 48 (the spawn limit) and now I lost a Angus Bull, he was also named and had been handfeed

**Comment by capnkirok** [comment]
Thanks for checking. Sounds like a bug / compat issue. Will come back if I have questions.

**Comment by Cilleh1989** [comment]
Hi, I know you are already investigating this issue, I told you about. And I was curious about how its going?
I don't know much about making a mod, so I can't give any ideas on where the issue could be.

Also today, after almost 12 hours of having the server open, I went from 2 cows, 2 bulls, 6 calves to 1 calf and 1 cow, all the races was representet. 
there is still no issue with the pigs or chickens.

**Comment by capnkirok** [comment]
Oooh, this really helps, that it's only affecting the cows. Thanks! We are in the middle of a big update, and plan to get this issue sorted with the rest. No ETA yet.

**Comment by WilliamtheChad** [comment]
I'm having a similar issue with just chickens...

**Comment by capnkirok** [comment]
Thanks guys, we're looking into this one.

**Comment by capnkirok** [comment]
Question back to @WilliamtheChad, @Cilleh1989 ... did you by chance have an existing server with vanilla animals, then you installed Animania, which then replaced your animals? And then they started disappearing? Or is this happening on fresh worlds?

**Comment by WilliamtheChad** [comment]
this was a fresh world, I think if may be related to the spawn limit.  These were hand fed chickens, that were actively breeding, but not named.  I don't know if I noticed a pattern to them vanishing.  I recall walking into my house and coming back out and the chickens were gone, 6 of them, but there were some 6 eggs still in the nests.  I was having issues with them glitching out of the pen I had made, using hatches for eas egg collection.  At first I figured it was just them getting loose, but I fixed the pen so they weren't glitching , then they just all vanished slowly.  There were previously around 20 chickens.  I collected more chickens and named these ones, they've since had offspring and seem to be multiplying just fine, but the same amount of game time has not passed, so time will tell.

**Comment by capnkirok** [comment]
Thanks! Late last night I discovered the root cause(s), combination of my own code and vanilla MC. Fix will be in the next release.

**Comment by Cilleh1989** [comment]
Hey, sry for the late answer, it has been a couple of stressful days.
For me it was a fresh world as well.
But good to hear that you found the cause of the problems, I'll look forward to th next release :)

**Comment by Cilleh1989** [comment]
Hey, its still happening. I just lost a Holstien cow, who where named and hand feed, and all the calves dissapired as well :-s
The spawn limit for cows in loaded chuncks is still 48 instead of 24.
I use animania version: 1.10.2-1.1.3.jar and forge version is the same (forge-1.10.2-12.18.3.2281)

**Comment by capnkirok** [comment]
Ok, time for a deeper look. I will download the mods and do some testing. 

Can you tell me... in this world where you lost an animal, can you try using a generic spawn egg from Minecraft of that animal type. Does an animal spawn or does is spawn nothing. You can only test this using a vanilla pig, cow, or chicken egg. So, since you lost cows... what happens if you try to spawn a vanilla cow?

**Comment by Cilleh1989** [comment]
Im so, so sorry that I worte earlier.. I didn't know that you guys had updatet from 1.1.13 to 1.1.14. 
It seem to have been fixed, I have been in a different area of the map (Same place as when I lost a cow in 1.1.13) and have been there  since I saw and applyed version 1.1.14, and I have lost 0 cows, bulls or calves, so far. 
I'm so sorry I jumped the sword without having the proper version active.
When I try to spawn a vanilla cow, I have 4 different cow eegs. 
Two with the same name: Spawn Cow both under Miscellaneous, An egg called Anti-Cow and one called Demon Cow.
When I spawn one of the first two, two things happen: 
1. It becomes a random type of Animania cow.
2. It looks like a normal vanilla cow, but when I smack it, it turns red and set the ground on fire.

**Comment by Cilleh1989** [comment]
Okey. Now just now, I was in the other area on the map, I just tp'ed back to check on my cows. And there was one missing. just gone, a Fresian cow. her mate and calf and other mating couple and their calves is still there.

**Comment by Cilleh1989** [comment]
One of the players from the server, told me that when we updated from 1.1.13 to 1.1.14, he lost a white peacock male.

**Comment by capnkirok** [comment]
Yeah, the one with the Peacock is possible, we had to fix something in the entity that may have done that.

**Comment by Cilleh1989** [comment]
Did you figure out what coursed the animals to disappear?

Den 29. jun. 2017 00.53 skrev "Purplicious_Cow" <notifications@github.com>:
